var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                                                                          x  ",
   "  x                          o                                               x  ",
   "  x                          o                                               x  ",
   "  x                         xxx             xxxxx         o o                x  ",
   "  x                                      xxxxxxxxx       xxxxxx              x  ",
   "  x              xxxxxx                 xxxxxxxxxx!!!!!!!!!xxxxxx       o    x  ",
   "  x  @       xxxxxxxxxx                xxxxxxxx!!!!!!!!!!!!!!!xxxx      o    x  ",
   "  xxxxxxxxxxxxxxxxxxxxx           xx  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                      x           xx!!x                                         ",
   "                      x!!!!!!!!!!!xx!!x                                         ",
   "                      x!!!!!!!!!!!xxxxx                                         ",
   "                      xxxxxxxxxxxxx                                             ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                  o                                                                               ",
   "                                                                                                                  ",
   "                                 xxx                                                                              ",
   "                                 x!x                  o  o  o  o                                                  ",
   "                                 xvxxx                                                                            ",
   "                                               x     xxxxxxxxxxxx                xxx         xxx                  ",
   "                                             xxx     xxxxxxxx                    x x o       x x                  ",
   "                                               x     xxxxx                         x o       x                    ",
   "                                               x     xxx                           xxx       x                    ",
   "                          o  o                 xx    xx                            x         x                    ",
   "                                               x     x                             x         x                    ",
   "                     xxxxxxxxxxxx   xxx        x     x                             x         x                    ",
   "                     xxxxxxxxxxxx   x          x     x                       xxxxxxxxx       x                    ",
   "             xx       xxxxxxxxxxx o x          x    xx    o                  x             o x                    ",
   "     @       x         xxxxxxxxxx   x!!!!!!!!!!x     x    o       xxxx   x   x               x                    ",
   "    xxx      x         xxxxxxxxxx o x!!!!!!!!!!x     x    o          x   xxxxx             xxx                    ",
   "    x x      x         xxxxxxxxxx   xx!!!!!!!!!x     x   xxxx        x     o                 x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xxx o  xx!!!!!!!!xx    x!!!!!!!!!!!!!!!x     o        =        x                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xxxx     xxxxxxxxxx     x!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xxxx o                 xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxx                     ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xxxx                  xx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxx                     ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!xxxx     xxxxxxxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                    ",
   "!!!!x x!!!!!!x!!!!!!!!!x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                    "],
  ["                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                        o xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                        x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                        x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                        x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                        x xxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                       xxxxxx!!!!!!!!!!!!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxx ",
   "                                       x xxxx!!!v!!!!!!v!!!!!!!!!!!!!xxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxx ",
   "                                       x xxxxxxx xxxxxx xxxxxvvxxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxx ",
   "                                     xxx xxxxxxx xxxxxx xxxxx  xxxxxxxxxxxxxxxxxxxxxxx!xxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                    xxxxxxxxxxxxxxxxxxvxxxxxxxxxxxxxxxxxxxxxx ",
   "                                             o      o     o         xxxxxxxxxxxxxxxxxx xxxxxxxxxxxxxxxxxxxxxx ",
   "                                             o      o     o         xxxxxxxxxxxxxx                  xx   xxxx ",
   "                                     xx   xxxxxx xxxxxx xxxxx    xxxxxxxxxxxxxxxxx                  xx   xxxx ",
   "                                      x   xxxxxx xxxxxxxxxxxx    xxxxxxxxxxxxxxxxx                  xx   xxxx ",
   "                                      x   xxxxxx xxxxxxxxxxxx                                     xxxxxx xxxx ",
   "                                      x   xxxxxx xxxxxxxxxxxx                                      xxxx  xxxx ",
   "                                   xxxxx  xxxxxx xxxxxxxxxxxx                                       xx   xxxx ",
   "                                      x   xxx            xxxxx                                       x    xxxx ",
   "                                      x   xxx            xxxxx                                           xxxx ",
   "                                      x   xxx      o     xxxxx                                           xxxx ",
   "                                     xx   xxx      o     xxxxx           =         xxxxxxxxxxxxxxxxxx  xxxxxx ",
   "                              o   o   x    xxxxx xxxx    xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "                                      x      xxx xxxx    xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "                             xxx xxx xxx x   xxx xxxxx   xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "                             x xxx x x xxx   xxx xxxxx   xxxxx xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "                             x                xx xxxxx             xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "                             xx                                         xxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  xxx                         x     x                                             xxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  x x                         x    xxx    xxxxxx xxxxxxxxxxxxxxxxxx         o o   xxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  x                           x    xxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx    o o   xxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  x                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  x                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  x                                       xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  x                                o o    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  x                           xx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxooxxxxxx ",
   "  x                           x    xxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  xxxxxx ",
   "  x                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  x      @                    x           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "           xxxxxxxxx                                                                                          ",
   "           x!!!!!!!x                                                                                          ",
   "             vvvvv                                                x                                           ",
   "                                       o            o  o  o       v                                           ",
   "                                       o           xxx                                                        ",
   "                                                  xxvxxxxxxx                                                  ",
   "                                                                                                             ",
   "                                                                         o                                    ",
   "                                      xxx                                o                                    ",
   "             o  o                                                       xxx                                   ",
   "             o  o                                                       xxx                                   ",
   "           xxxxxxxxxx       xxxxxx                          xxx        xxxx                                   ",
   "                                                       xxxxxxxx        xxxx            o                      ",
   "                                                            xxx        xxxx            o                      ",
   "                       o    o         o                     xxx        xxxx            x                      ",
   "                       o         o    =     o               xxx        xxxx            x                      ",
   "                      xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx       xxx                        x                   xxx",
   "                                                            xxx                        x                   xxx",
   "                                                            xxx                        x                   xxx",
   "                                                            xxx                        x                   xxx",
   "                                                            xxx                        x                   xxx",
   "            @                                               xxx                        x               oo  xxx",
   "        xxxxxxxxxx                                          xxx                        x              oooo xxx",
   "                                                            xxx                        x               oo  xxx",
   "                                                            xxx                        x                   xxx",
   "                                                            xxx                        xxxxxxxxxxxxxxxxxxxxxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!!!x!x!x!!x!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x!x!x!x!xx!x!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxx!!x!x!xx!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
